"""Add is_employee column to Usuario

Revision ID: 7d67aeba8d00
Revises: 58e4d42d75a4
Create Date: 2025-06-18 17:08:59.411609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d67aeba8d00'
down_revision = '58e4d42d75a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_employee', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_employee')

    # ### end Alembic commands ###
